#application: weighty-smoke-142717
#version: 1
runtime: php55
api_version: 1

handlers:
- url: /(.+\.(ico|jpg|png|gif))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif))$
  application_readable: true

- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$
  application_readable: true

- url: /(.+\.php)$
  script: \1

- url: /.*
  script: index.php

env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: /cloudsql/weighty-smoke-142717:us-central1:autocomplete1;dbname=autoComplete
  MYSQL_USER: root
  MYSQL_PASSWORD: ''
