<?php

$productInfo = array(
array( "label" => "Absolute Black 2CM", "value" => "2033" ),
array( "label" => "Absolute Black Honed 2CM", "value" => "2096" ),
array( "label" => "Absolute Black Leather 3CM", "value" => "1784" ),
array( "label" => "Alaska White", "value" => "1953" ),
array( "label" => "Amber Gold Onyx 2CM", "value" => "843" ),
array( "label" => "Andromeda White", "value" => "1326" ),
array( "label" => "Angola Black", "value" => "1483" ),
array( "label" => "Angola Silver", "value" => "1308" ),
array( "label" => "Arco Iris Onyx 2CM", "value" => "841" ),
array( "label" => "Ash Blue", "value" => "1743" ),
array( "label" => "Astoria", "value" => "1980" ),
array( "label" => "Athens Gray 2CM", "value" => "1897" ),
array( "label" => "Autumn River", "value" => "1702" ),
array( "label" => "Avoria White", "value" => "1641" ),
array( "label" => "Azul Aran", "value" => "1660" ),
array( "label" => "Azul Gray Quartz", "value" => "1956" ),
array( "label" => "Azul Platino", "value" => "2118" ),
array( "label" => "Azzurite", "value" => "1693" ),
array( "label" => "Bahama White", "value" => "2150" ),
array( "label" => "Bethel White", "value" => "1455" ),
array( "label" => "Bethel White", "value" => "1559" ),
array( "label" => "Bianco Carrara 2CM", "value" => "1739" ),
array( "label" => "Bianco Carrara Honed 3CM", "value" => "1334" ),
array( "label" => "Bianco Gem", "value" => "1389" ),
array( "label" => "Bianco Gioia 3CM", "value" => "1402" ),
array( "label" => "Bianco Neve", "value" => "2121" ),
array( "label" => "Bianco Rhino", "value" => "2044" ),
array( "label" => "Bianco Romano", "value" => "1434" ),
array( "label" => "Bianco Sardo", "value" => "2131" ),
array( "label" => "Black Beauty", "value" => "623" ),
array( "label" => "Black Fantasy", "value" => "1814" ),
array( "label" => "Black Forest", "value" => "2038" ),
array( "label" => "Black Fusion", "value" => "1249" ),
array( "label" => "Black Galaxy ", "value" => "1981" ),
array( "label" => "Black Impala", "value" => "1274" ),
array( "label" => "Black Marinace", "value" => "1397" ),
array( "label" => "Black Mosaic", "value" => "1884" ),
array( "label" => "Black Pearl ", "value" => "2155" ),
array( "label" => "Black Pearl Leather", "value" => "2156" ),
array( "label" => "Blue Bahia", "value" => "1560" ),
array( "label" => "Blue Calcite", "value" => "1947" ),
array( "label" => "Blue Flowers", "value" => "1730" ),
array( "label" => "Blue In The Night", "value" => "1359" ),
array( "label" => "Blue Luise", "value" => "1382" ),
array( "label" => "Blue Night", "value" => "1745" ),
array( "label" => "Blue Pearl GT", "value" => "1614" ),
array( "label" => "Blue Pearl Marina ", "value" => "986" ),
array( "label" => "Blue Pearl Ocean ", "value" => "1640" ),
array( "label" => "Blue Pearl Original", "value" => "2024" ),
array( "label" => "Blue Pearl Royale", "value" => "1785" ),
array( "label" => "Blue Soapstone", "value" => "1767" ),
array( "label" => "Bordeaux River", "value" => "1857" ),
array( "label" => "Botticino Fiorito 3CM", "value" => "797" ),
array( "label" => "Brass Blue", "value" => "2153" ),
array( "label" => "Brass Blue Leather", "value" => "2154" ),
array( "label" => "Brazilian Black", "value" => "1762" ),
array( "label" => "Brown Antique", "value" => "1823" ),
array( "label" => "Brown Antique Leather", "value" => "1847" ),
array( "label" => "Brownie", "value" => "1970" ),
array( "label" => "Butterfly Beige", "value" => "2011" ),
array( "label" => "Butterfly Green", "value" => "1971" ),
array( "label" => "Calacatta 3CM", "value" => "1852" ),
array( "label" => "Calacatta Bella", "value" => "1752" ),
array( "label" => "Calacatta Europa", "value" => "1727" ),
array( "label" => "Calacatta Gold", "value" => "1024" ),
array( "label" => "Calacatta Light 3CM", "value" => "1991" ),
array( "label" => "Calacatta Michelangelo Quartz", "value" => "1954" ),
array( "label" => "Cambrian Black Antique", "value" => "1958" ),
array( "label" => "Cambrian Black Polished", "value" => "2074" ),
array( "label" => "Cappuccino Onyx 2CM", "value" => "842" ),
array( "label" => "Carioca Gold", "value" => "1315" ),
array( "label" => "Churchill Soapstone", "value" => "2104" ),
array( "label" => "Cialo Fantasy", "value" => "1374" ),
array( "label" => "Cleopatra", "value" => "1957" ),
array( "label" => "Cleopatra Leather", "value" => "1911" ),
array( "label" => "Cleti Spring", "value" => "2134" ),
array( "label" => "Coast Green", "value" => "1457" ),
array( "label" => "Colonial Fantasy", "value" => "2170" ),
array( "label" => "Colonial Treasure", "value" => "1273" ),
array( "label" => "Colonial White", "value" => "2083" ),
array( "label" => "Copenhagen", "value" => "1746" ),
array( "label" => "Corteccia ", "value" => "1937" ),
array( "label" => "Costa Smeralda", "value" => "1661" ),
array( "label" => "Crema Antartica", "value" => "2071" ),
array( "label" => "Crema Bordeaux", "value" => "1747" ),
array( "label" => "Crema Caramel", "value" => "2140" ),
array( "label" => "Crema Marfil Ivory 2CM", "value" => "1933" ),
array( "label" => "Cristallo", "value" => "1918" ),
array( "label" => "Damasco White", "value" => "2007" ),
array( "label" => "Delicatus Gold", "value" => "1709" ),
array( "label" => "Desert Brown", "value" => "2063" ),
array( "label" => "Dolce Vita ", "value" => "1939" ),
array( "label" => "Eagle White", "value" => "1786" ),
array( "label" => "Earth Glitter", "value" => "1722" ),
array( "label" => "Elegant Dune", "value" => "1019" ),
array( "label" => "Emerald Pearl", "value" => "2159" ),
array( "label" => "Emperador Dark 2CM", "value" => "1935" ),
array( "label" => "Everest", "value" => "2036" ),
array( "label" => "Fantasy Brown", "value" => "1532" ),
array( "label" => "Fantasy Brown Leather", "value" => "2127" ),
array( "label" => "Ferrato", "value" => "1603" ),
array( "label" => "Fusion", "value" => "2178" ),
array( "label" => "Galaxy White", "value" => "1988" ),
array( "label" => "Ghiblee", "value" => "2010" ),
array( "label" => "Giallo Fiorito", "value" => "2176" ),
array( "label" => "Giallo Napoleone", "value" => "1567" ),
array( "label" => "Giallo Napoli", "value" => "2125" ),
array( "label" => "Giallo Ornamental", "value" => "2177" ),
array( "label" => "Giallo Ornamental Light ", "value" => "2133" ),
array( "label" => "Giallo Veneziano", "value" => "1836" ),
array( "label" => "Giallo Vicenza", "value" => "2062" ),
array( "label" => "Golden Beach", "value" => "1793" ),
array( "label" => "Golden King", "value" => "2091" ),
array( "label" => "Golden Lightning", "value" => "1521" ),
array( "label" => "Golden Typhoon", "value" => "1989" ),
array( "label" => "Gray Soapstone Honed ", "value" => "1950" ),
array( "label" => "Gray Soapstone Original", "value" => "2124" ),
array( "label" => "Green Marinace", "value" => "1331" ),
array( "label" => "Green Pearl", "value" => "1894" ),
array( "label" => "Green River", "value" => "1058" ),
array( "label" => "Green Soapstone Honed", "value" => "1768" ),
array( "label" => "Guidoni Light", "value" => "2147" ),
array( "label" => "Ice Crystal", "value" => "2041" ),
array( "label" => "Ice Flakes", "value" => "1620" ),
array( "label" => "Ice White", "value" => "1691" ),
array( "label" => "Indian Dakota Mahogany", "value" => "1867" ),
array( "label" => "Ivory Fantasy (Dark)", "value" => "1591" ),
array( "label" => "Ivory Gold", "value" => "1270" ),
array( "label" => "Jet Mist Leather", "value" => "2142" ),
array( "label" => "Jet Mist Polished", "value" => "2143" ),
array( "label" => "Jungle Green Soapstone", "value" => "935" ),
array( "label" => "Juparana Colombo", "value" => "1467" ),
array( "label" => "Juparana Vyara", "value" => "1498" ),
array( "label" => "Kashmir Gold", "value" => "1352" ),
array( "label" => "Kashmir White", "value" => "1555" ),
array( "label" => "Kodiak Antique", "value" => "1287" ),
array( "label" => "Labradorite Mulitcolor", "value" => "1376" ),
array( "label" => "Lapidus", "value" => "1872" ),
array( "label" => "Lennon", "value" => "2019" ),
array( "label" => "Madura Gold", "value" => "1106" ),
array( "label" => "Marfil Quartz", "value" => "1955" ),
array( "label" => "Mascarello", "value" => "919" ),
array( "label" => "Matrix 3D", "value" => "1669" ),
array( "label" => "Millenium Cream", "value" => "2028" ),
array( "label" => "Minsk Green", "value" => "1190" ),
array( "label" => "Monte Cristo", "value" => "2087" ),
array( "label" => "Montecarlo", "value" => "1834" ),
array( "label" => "Moon Light", "value" => "1595" ),
array( "label" => "Moon White", "value" => "2166" ),
array( "label" => "Nacarado", "value" => "1778" ),
array( "label" => "Naica Quartz", "value" => "1832" ),
array( "label" => "Namibian Gold", "value" => "1362" ),
array( "label" => "Namibian Green", "value" => "1247" ),
array( "label" => "Neptune Bordeaux", "value" => "1542" ),
array( "label" => "New Caledonia", "value" => "2110" ),
array( "label" => "New Kashmir White", "value" => "1999" ),
array( "label" => "New Sienna Bordeaux", "value" => "1075" ),
array( "label" => "New Venetian Gold", "value" => "2115" ),
array( "label" => "Ocean Aqua", "value" => "2008" ),
array( "label" => "Oceanic Bordeaux ", "value" => "1263" ),
array( "label" => "Ouro Brasil", "value" => "2137" ),
array( "label" => "Paradiso Bash", "value" => "2049" ),
array( "label" => "Paradiso Classic", "value" => "1497" ),
array( "label" => "Peacock Amber", "value" => "1996" ),
array( "label" => "Peacock Green ", "value" => "2144" ),
array( "label" => "Peacock Light", "value" => "2050" ),
array( "label" => "Perla Venata", "value" => "2103" ),
array( "label" => "Persa Blue", "value" => "1418" ),
array( "label" => "Piracema White", "value" => "2002" ),
array( "label" => "Rainforest Green ", "value" => "1946" ),
array( "label" => "Red Mattisse Onyx 2CM", "value" => "831" ),
array( "label" => "River Valley", "value" => "1917" ),
array( "label" => "River White", "value" => "2169" ),
array( "label" => "Rocky Mountain", "value" => "1429" ),
array( "label" => "Rosewood", "value" => "1993" ),
array( "label" => "Santa Cecilia", "value" => "2171" ),
array( "label" => "Santa Cecilia Classic", "value" => "2162" ),
array( "label" => "Santa Cecilia Gold", "value" => "1537" ),
array( "label" => "Santa Cecilia Light ", "value" => "2157" ),
array( "label" => "Santa Cecilia Yellow", "value" => "1781" ),
array( "label" => "Sapphire Blue", "value" => "2165" ),
array( "label" => "Saturnia Gold", "value" => "1791" ),
array( "label" => "Shivakashi", "value" => "1979" ),
array( "label" => "Sienna Beige", "value" => "1090" ),
array( "label" => "Sienna Bordeaux", "value" => "2179" ),
array( "label" => "Silver White", "value" => "2149" ),
array( "label" => "Smokey Gray", "value" => "2029" ),
array( "label" => "Soapstone Antolini", "value" => "1064" ),
array( "label" => "Solarius", "value" => "2175" ),
array( "label" => "Spike Black ", "value" => "1466" ),
array( "label" => "Spike Black Leather", "value" => "1215" ),
array( "label" => "Statuarietto ", "value" => "1248" ),
array( "label" => "Steel Gray ", "value" => "2117" ),
array( "label" => "Steel Gray Leather", "value" => "2164" ),
array( "label" => "Striato 2CM", "value" => "1976" ),
array( "label" => "Super White", "value" => "1967" ),
array( "label" => "Super White Calacatta", "value" => "1919" ),
array( "label" => "Taj Mahal", "value" => "1108" ),
array( "label" => "Tan Brown", "value" => "2151" ),
array( "label" => "Thunder White", "value" => "2128" ),
array( "label" => "Titanium", "value" => "1489" ),
array( "label" => "Tropical Green", "value" => "1983" ),
array( "label" => "Typhoon Bordeaux", "value" => "1913" ),
array( "label" => "Typhoon Green", "value" => "1757" ),
array( "label" => "Ubatuba", "value" => "2138" ),
array( "label" => "Ubatuba Marbrasa", "value" => "2123" ),
array( "label" => "Vanilla", "value" => "1961" ),
array( "label" => "Verde Borgogna", "value" => "1776" ),
array( "label" => "Verde Fantastico", "value" => "1165" ),
array( "label" => "Vintage", "value" => "1111" ),
array( "label" => "Viscon White", "value" => "2136" ),
array( "label" => "Volga Blue", "value" => "2160" ),
array( "label" => "Vyara Exotica", "value" => "1742" ),
array( "label" => "White Fortaleza", "value" => "2167" ),
array( "label" => "White Macaubas", "value" => "1590" ),
array( "label" => "White Onyx 2CM", "value" => "832" ),
array( "label" => "White Pearl", "value" => "1505" ),
array( "label" => "White Shore", "value" => "2141" ),
array( "label" => "White Summit", "value" => "2056" ),
array( "label" => "Wonder Gray", "value" => "1998" )
);


?>
